### ISSUE TITLE
ROADMAP of MetaSeg

### ISSUE THREAD

**Issue by kadirnar** [kadirnar/segment-anything-video#6]
- [ ] https://github.com/kadirnar/segment-anything-video/issues/54
- [x] #8
- [x] #53
- [x] https://github.com/kadirnar/segment-anything-video/issues/37
- [x] https://github.com/kadirnar/segment-anything-video/issues/24
- [ ] #60
- [x] #51
- [x] #49
- [x] #7
- [x] #27
- [x] #19
- [x] #9
- [x] #11

**Comment by bhack** [comment]
It could be useful to have Video also in  https://github.com/kadirnar/segment-anything-video/blob/15e7549af39bae5e31b3481bad68865b00bb1d19/metaseg/mask_predictor.py#L107

**Comment by kadirnar** [comment]
@bhack ,

Why do you want video? You will need to constantly update the bbox or point points.

**Comment by bhack** [comment]
> @bhack ,
> 
> Why do you want video? You will need to constantly update the bbox or point points.

We could give this supervision to mainly test the temporal stability cause I think it is the main problem applying this in videos without learning the propagation.

**Comment by kadirnar** [comment]
> > @bhack ,
> > Why do you want a video? You will need to constantly update the bbox or point points.
> 
> We could give this supervision to mainly test the temporal stability cause I think it is the main problem applying this in videos without learning the propagation.
> 
> Edit: see [#46 (comment)](https://github.com/kadirnar/segment-anything-video/issues/46#issuecomment-1505186882)

I added video support but don't plan to add a tracker. This is an open source project and I am working alone. It is difficult to develop in Colab Pro.

**Comment by kadirnar** [comment]
> hello, how can we use it as a background remover like REMBG

I will add it this week.
